version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - ./kurisudb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kurisu
      POSTGRES_PASSWORD: dev123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kurisu"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  kurisu:
    build: .
    image: kurisutest
    environment:
      KURISU_TOKEN_FILE: /run/secrets/kurisu_token
      DB_USER: kurisu
      DB_PASSWORD: dev123
    secrets:
      - kurisu_token
    depends_on:
      db:
        condition: service_healthy
    restart: always

secrets:
  kurisu_token:
    file: ./token.txt
